name: stoic_app
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  flutter_markdown: ^0.7.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/stack_book.png"
  adaptive_icon_background: "#2C2C2C"  # Fondo oscuro elegante
  adaptive_icon_foreground: "assets/images/stack_book.png"

flutter:
  uses-material-design: true
  
  # Assets (im√°genes, fuentes, etc.)
  assets:
    - assets/images/
